# Generated by Django 2.2.1 on 2019-06-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190630_1710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
